ALTER TABLE clients ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE clients ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE clients ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';

ALTER TABLE books ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE books ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE books ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';

ALTER TABLE users ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';